### ISSUE TITLE
Plugin breakes images

### ISSUE THREAD

**Issue by limpbrains** [molforp/transfer-webpack-plugin#1]
When I'm trying to transfer folder with png image it gets corruped. File size changes and browser can't display it.

**Comment by limpbrains** [comment]
```
build/public/img$ file white_logo.png 
white_logo.png: data
```

insted of 

```
src/img$ file white_logo.png 
white_logo.png: PNG image data, 98 x 17, 8-bit/color RGBA, non-interlaced
```

**Comment by dkokorev90** [comment]
with png only? what about other types? I'll check it soon

**Comment by kevinrenskers** [comment]
I have it with JPG images too

**Comment by AsaAyers** [comment]
I have a PR up for the fix. The problem is that `node-dir` is providing all files as if they were strings. This ends up providing a string representation of any binary files you attempt to copy, which provides you with a corrupted file.
